require: rubocop-rake

Style/StringLiterals:
  EnforcedStyle: double_quotes
  Enabled: true
# Allow classes longer than 100 lines of code
Metrics/ClassLength:
  Max: 250 # or whatever ends up being appropriate

Layout/LineLength:
  Max: 100
  # To make it possible to copy or click on URIs in the code, we allow lines
  # containing a URI to be longer than Max.
  AllowHeredoc: true
  AllowURI: true
  URISchemes:
    - http
    - https
AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
